#:schema https://json.schemastore.org/prettierrc

arrowParens = "always"
bracketSameLine = false
bracketSpacing = true
embeddedLanguageFormatting = "auto"
experimentalTernaries = true
htmlWhitespaceSensitivity = "ignore"
plugins = [
	"prettier-plugin-organize-imports",
	"prettier-plugin-pkg",
	"prettier-plugin-sh",
	"prettier-plugin-toml",
]
printWidth = 100
proseWrap = "always"
semi = false
singleQuote = false
tabWidth = 2
trailingComma = "all"


binaryNextLine = true
functionNextLine = false
keepComments = true
minify = false
spaceRedirects = false
switchCaseIndent = false


alignComments = true
alignEntries = false
allowedBlankLines = 2
arrayAutoCollapse = true
arrayAutoExpand = true
compactArrays = true
compactEntries = false
compactInlineTables = false
indentEntries = false
indentTables = false
reorderKeys = true


[[overrides]]
files = ["*.js", "*.ts", "*.css", "*.sh", "*.bash", "*.toml"]
options = { printWidth = 98, useTabs = true }


[[overrides]]
files = ["*.js", "*.ts"]
options = { parser = "typescript" }


[[overrides]]
files = ["*.json"]
options = { parser = "jsonc", trailingComma = "none" }


[[overrides]]
files = ["package.json"]
options = { parser = "json-stringify" }
